use embassy_rp::{
    Peri, Peripherals,
    gpio::Pin,
    peripherals::{
        ADC, ADC_TEMP_SENSOR, CORE1, DMA_CH0, DMA_CH1, DMA_CH2, DMA_CH3, DMA_CH4, DMA_CH5, DMA_CH6,
        DMA_CH7, DMA_CH8, DMA_CH9, DMA_CH10, DMA_CH11, DMA_CH12, DMA_CH13, DMA_CH14, DMA_CH15,
        FLASH, I2C0, I2C1, PIN_0, PIN_1, PIN_2, PIN_3, PIN_4, PIN_5, PIN_6, PIN_7, PIN_8, PIN_9,
        PIN_10, PIN_11, PIN_12, PIN_13, PIN_14, PIN_15, PIN_16, PIN_17, PIN_18, PIN_19, PIN_20,
        PIN_21, PIN_22, PIN_23, PIN_24, PIN_25, PIN_26, PIN_27, PIN_28, PIN_29, PIN_30, PIN_31,
        PIN_32, PIN_33, PIN_34, PIN_35, PIN_36, PIN_37, PIN_38, PIN_39, PIN_40, PIN_41, PIN_42,
        PIN_43, PIN_44, PIN_45, PIN_46, PIN_47, PIO0, PIO1, PIO2, PWM_SLICE0, PWM_SLICE1,
        PWM_SLICE2, PWM_SLICE3, PWM_SLICE4, PWM_SLICE5, PWM_SLICE6, PWM_SLICE7, PWM_SLICE8,
        PWM_SLICE9, PWM_SLICE10, PWM_SLICE11, RTC, SPI0, SPI1, TRNG, UART0, UART1, USB, WATCHDOG,
    },
};

pub struct DutPins {
    pub d00: Peri<'static, PIN_0>,
    pub d01: Peri<'static, PIN_1>,
    pub d02: Peri<'static, PIN_2>,
    pub d03: Peri<'static, PIN_3>,
    pub d04: Peri<'static, PIN_4>,
    pub d05: Peri<'static, PIN_5>,
    pub d06: Peri<'static, PIN_6>,
    pub d07: Peri<'static, PIN_7>,
    pub d08: Peri<'static, PIN_8>,
    pub d09: Peri<'static, PIN_9>,
    pub d10: Peri<'static, PIN_10>,
    pub d11: Peri<'static, PIN_11>,
    pub d12: Peri<'static, PIN_12>,
    pub d13: Peri<'static, PIN_13>,
    pub d14: Peri<'static, PIN_14>,
    pub d15: Peri<'static, PIN_15>,

    pub d10_alt: Peri<'static, PIN_25>,
    pub d11_alt: Peri<'static, PIN_24>,
    pub d12_alt: Peri<'static, PIN_27>,
    pub d13_alt: Peri<'static, PIN_26>,

    pub a0: Peri<'static, PIN_40>,
    pub a1: Peri<'static, PIN_41>,
    pub a2: Peri<'static, PIN_42>,
    pub a3: Peri<'static, PIN_43>,
    pub a4: Peri<'static, PIN_44>,
    pub a5: Peri<'static, PIN_45>,
    pub a6: Peri<'static, PIN_46>,

    pub pwm0: Peri<'static, PIN_39>,
    pub pwm1: Peri<'static, PIN_38>,
    pub pwm2: Peri<'static, PIN_37>,
    pub pwm3: Peri<'static, PIN_36>,
    pub pwm4: Peri<'static, PIN_35>,
    pub pwm5: Peri<'static, PIN_34>,
    pub pwm6: Peri<'static, PIN_33>,

    pub reset: Peri<'static, PIN_32>,
}

pub struct ShieldPins {
    pub usb_host_en: Peri<'static, PIN_16>,
    pub usb_host_sel: Peri<'static, PIN_17>,
    pub usb_host_dp: Peri<'static, PIN_18>,
    pub usb_host_dn: Peri<'static, PIN_19>,

    pub usb0_en: Peri<'static, PIN_20>,
    pub usb0_flag: Peri<'static, PIN_21>,
    pub usb1_en: Peri<'static, PIN_22>,
    pub usb1_flag: Peri<'static, PIN_23>,

    pub todi: Peri<'static, PIN_28>,
    pub tido: Peri<'static, PIN_29>,

    pub sda: Peri<'static, PIN_30>,
    pub scl: Peri<'static, PIN_31>,

    pub led: Peri<'static, PIN_47>,
}

#[expect(non_snake_case, reason = "Match names of original Peripherals struct")]
pub struct ShieldPeripherals {
    pub UART0: Peri<'static, UART0>,
    pub I2C1: Peri<'static, I2C1>,
    pub DMA_CH14: Peri<'static, DMA_CH14>,
    pub DMA_CH15: Peri<'static, DMA_CH15>,
    pub USB: Peri<'static, USB>,

    pub PWM_SLICE8: Peri<'static, PWM_SLICE8>,
    pub PWM_SLICE9: Peri<'static, PWM_SLICE9>,
    pub PWM_SLICE10: Peri<'static, PWM_SLICE10>,
    pub PWM_SLICE11: Peri<'static, PWM_SLICE11>,

    pub ADC: Peri<'static, ADC>,
    pub ADC_TEMP_SENSOR: Peri<'static, ADC_TEMP_SENSOR>,
}

#[expect(non_snake_case, reason = "Match names of original Peripherals struct")]
pub struct OtherPeripherals {
    pub UART1: Peri<'static, UART1>,
    pub SPI0: Peri<'static, SPI0>,
    pub SPI1: Peri<'static, SPI1>,
    pub I2C0: Peri<'static, I2C0>,
    pub DMA_CH0: Peri<'static, DMA_CH0>,
    pub DMA_CH1: Peri<'static, DMA_CH1>,
    pub DMA_CH2: Peri<'static, DMA_CH2>,
    pub DMA_CH3: Peri<'static, DMA_CH3>,
    pub DMA_CH4: Peri<'static, DMA_CH4>,
    pub DMA_CH5: Peri<'static, DMA_CH5>,
    pub DMA_CH6: Peri<'static, DMA_CH6>,
    pub DMA_CH7: Peri<'static, DMA_CH7>,
    pub DMA_CH8: Peri<'static, DMA_CH8>,
    pub DMA_CH9: Peri<'static, DMA_CH9>,
    pub DMA_CH10: Peri<'static, DMA_CH10>,
    pub DMA_CH11: Peri<'static, DMA_CH11>,
    pub DMA_CH12: Peri<'static, DMA_CH12>,
    pub DMA_CH13: Peri<'static, DMA_CH13>,
    pub PWM_SLICE0: Peri<'static, PWM_SLICE0>,
    pub PWM_SLICE1: Peri<'static, PWM_SLICE1>,
    pub PWM_SLICE2: Peri<'static, PWM_SLICE2>,
    pub PWM_SLICE3: Peri<'static, PWM_SLICE3>,
    pub PWM_SLICE4: Peri<'static, PWM_SLICE4>,
    pub PWM_SLICE5: Peri<'static, PWM_SLICE5>,
    pub PWM_SLICE6: Peri<'static, PWM_SLICE6>,
    pub PWM_SLICE7: Peri<'static, PWM_SLICE7>,
    pub RTC: Peri<'static, RTC>,
    pub FLASH: Peri<'static, FLASH>,
    pub CORE1: Peri<'static, CORE1>,
    pub PIO0: Peri<'static, PIO0>,
    pub PIO1: Peri<'static, PIO1>,
    pub PIO2: Peri<'static, PIO2>,
    pub WATCHDOG: Peri<'static, WATCHDOG>,
    pub TRNG: Peri<'static, TRNG>,
}

pub fn split_peripherals(
    p: Peripherals,
) -> (ShieldPins, DutPins, ShieldPeripherals, OtherPeripherals) {
    let Peripherals {
        PIN_0,
        PIN_1,
        PIN_2,
        PIN_3,
        PIN_4,
        PIN_5,
        PIN_6,
        PIN_7,
        PIN_8,
        PIN_9,
        PIN_10,
        PIN_11,
        PIN_12,
        PIN_13,
        PIN_14,
        PIN_15,
        PIN_16,
        PIN_17,
        PIN_18,
        PIN_19,
        PIN_20,
        PIN_21,
        PIN_22,
        PIN_23,
        PIN_24,
        PIN_25,
        PIN_26,
        PIN_27,
        PIN_28,
        PIN_29,
        PIN_30,
        PIN_31,
        PIN_32,
        PIN_33,
        PIN_34,
        PIN_35,
        PIN_36,
        PIN_37,
        PIN_38,
        PIN_39,
        PIN_40,
        PIN_41,
        PIN_42,
        PIN_43,
        PIN_44,
        PIN_45,
        PIN_46,
        PIN_47,
        PIN_QSPI_SCLK: _,
        PIN_QSPI_SS: _,
        PIN_QSPI_SD0: _,
        PIN_QSPI_SD1: _,
        PIN_QSPI_SD2: _,
        PIN_QSPI_SD3: _,
        UART0,
        UART1,
        SPI0,
        SPI1,
        QMI_CS1: _,
        I2C0,
        I2C1,
        DMA_CH0,
        DMA_CH1,
        DMA_CH2,
        DMA_CH3,
        DMA_CH4,
        DMA_CH5,
        DMA_CH6,
        DMA_CH7,
        DMA_CH8,
        DMA_CH9,
        DMA_CH10,
        DMA_CH11,
        DMA_CH12,
        DMA_CH13,
        DMA_CH14,
        DMA_CH15,
        PWM_SLICE0,
        PWM_SLICE1,
        PWM_SLICE2,
        PWM_SLICE3,
        PWM_SLICE4,
        PWM_SLICE5,
        PWM_SLICE6,
        PWM_SLICE7,
        PWM_SLICE8,
        PWM_SLICE9,
        PWM_SLICE10,
        PWM_SLICE11,
        USB,
        RTC,
        FLASH,
        ADC,
        ADC_TEMP_SENSOR,
        CORE1,
        PIO0,
        PIO1,
        PIO2,
        WATCHDOG,
        BOOTSEL: _,
        TRNG,
    } = p;

    (
        ShieldPins {
            usb_host_en: PIN_16,
            usb_host_sel: PIN_17,
            usb_host_dp: PIN_18,
            usb_host_dn: PIN_19,
            usb0_en: PIN_20,
            usb0_flag: PIN_21,
            usb1_en: PIN_22,
            usb1_flag: PIN_23,
            todi: PIN_28,
            tido: PIN_29,
            sda: PIN_30,
            scl: PIN_31,
            led: PIN_47,
        },
        DutPins {
            d00: PIN_0,
            d01: PIN_1,
            d02: PIN_2,
            d03: PIN_3,
            d04: PIN_4,
            d05: PIN_5,
            d06: PIN_6,
            d07: PIN_7,
            d08: PIN_8,
            d09: PIN_9,
            d10: PIN_10,
            d11: PIN_11,
            d12: PIN_12,
            d13: PIN_13,
            d14: PIN_14,
            d15: PIN_15,
            d10_alt: PIN_25,
            d11_alt: PIN_24,
            d12_alt: PIN_27,
            d13_alt: PIN_26,
            a0: PIN_40,
            a1: PIN_41,
            a2: PIN_42,
            a3: PIN_43,
            a4: PIN_44,
            a5: PIN_45,
            a6: PIN_46,
            pwm0: PIN_39,
            pwm1: PIN_38,
            pwm2: PIN_37,
            pwm3: PIN_36,
            pwm4: PIN_35,
            pwm5: PIN_34,
            pwm6: PIN_33,
            reset: PIN_32,
        },
        ShieldPeripherals {
            UART0,
            I2C1,
            DMA_CH14,
            DMA_CH15,
            USB,
            PWM_SLICE8,
            PWM_SLICE9,
            PWM_SLICE10,
            PWM_SLICE11,
            ADC,
            ADC_TEMP_SENSOR,
        },
        OtherPeripherals {
            UART1,
            SPI0,
            SPI1,
            I2C0,
            DMA_CH0,
            DMA_CH1,
            DMA_CH2,
            DMA_CH3,
            DMA_CH4,
            DMA_CH5,
            DMA_CH6,
            DMA_CH7,
            DMA_CH8,
            DMA_CH9,
            DMA_CH10,
            DMA_CH11,
            DMA_CH12,
            DMA_CH13,
            PWM_SLICE0,
            PWM_SLICE1,
            PWM_SLICE2,
            PWM_SLICE3,
            PWM_SLICE4,
            PWM_SLICE5,
            PWM_SLICE6,
            PWM_SLICE7,
            RTC,
            FLASH,
            CORE1,
            PIO0,
            PIO1,
            PIO2,
            WATCHDOG,
            TRNG,
        },
    )
}

pub struct NamedPin<P: Naming>(pub P);

impl<P: Naming> defmt::Format for NamedPin<P> {
    fn format(&self, fmt: defmt::Formatter) {
        defmt::write!(fmt, "{} (Pin {})", self.0.name(), self.0.pin())
    }
}

#[expect(non_camel_case_types, reason = "match struct names")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, defmt::Format)]
pub enum PinName {
    usb_host_en = 16,
    usb_host_sel = 17,
    usb_host_dp = 18,
    usb_host_dn = 19,
    usb0_en = 20,
    usb0_flag = 21,
    usb1_en = 22,
    usb1_flag = 23,
    todi = 28,
    tido = 29,
    sda = 30,
    scl = 31,
    led = 47,
    d00 = 0,
    d01 = 1,
    d02 = 2,
    d03 = 3,
    d04 = 4,
    d05 = 5,
    d06 = 6,
    d07 = 7,
    d08 = 8,
    d09 = 9,
    d10 = 10,
    d11 = 11,
    d12 = 12,
    d13 = 13,
    d14 = 14,
    d15 = 15,
    d10_alt = 25,
    d11_alt = 24,
    d12_alt = 27,
    d13_alt = 26,
    a0 = 40,
    a1 = 41,
    a2 = 42,
    a3 = 43,
    a4 = 44,
    a5 = 45,
    a6 = 46,
    pwm0 = 39,
    pwm1 = 38,
    pwm2 = 37,
    pwm3 = 36,
    pwm4 = 35,
    pwm5 = 34,
    pwm6 = 33,
    reset = 32,
}

pub trait Naming: Pin {
    fn name(&self) -> PinName;
}

impl<P: Pin> Naming for P {
    fn name(&self) -> PinName {
        match self.pin() {
            16 => PinName::usb_host_en,
            17 => PinName::usb_host_sel,
            18 => PinName::usb_host_dp,
            19 => PinName::usb_host_dn,
            20 => PinName::usb0_en,
            21 => PinName::usb0_flag,
            22 => PinName::usb1_en,
            23 => PinName::usb1_flag,
            28 => PinName::todi,
            29 => PinName::tido,
            30 => PinName::sda,
            31 => PinName::scl,
            47 => PinName::led,
            0 => PinName::d00,
            1 => PinName::d01,
            2 => PinName::d02,
            3 => PinName::d03,
            4 => PinName::d04,
            5 => PinName::d05,
            6 => PinName::d06,
            7 => PinName::d07,
            8 => PinName::d08,
            9 => PinName::d09,
            10 => PinName::d10,
            11 => PinName::d11,
            12 => PinName::d12,
            13 => PinName::d13,
            14 => PinName::d14,
            15 => PinName::d15,
            25 => PinName::d10_alt,
            24 => PinName::d11_alt,
            27 => PinName::d12_alt,
            26 => PinName::d13_alt,
            40 => PinName::a0,
            41 => PinName::a1,
            42 => PinName::a2,
            43 => PinName::a3,
            44 => PinName::a4,
            45 => PinName::a5,
            46 => PinName::a6,
            39 => PinName::pwm0,
            38 => PinName::pwm1,
            37 => PinName::pwm2,
            36 => PinName::pwm3,
            35 => PinName::pwm4,
            34 => PinName::pwm5,
            33 => PinName::pwm6,
            32 => PinName::reset,
            _ => defmt::unreachable!(),
        }
    }
}
